#!/bin/bash
# Compile given assembly and run main_tb.integrate test on it.
# don't forget to add 'end' at the end to halt.
#
# Usage: integrate </path/to/input.asm
# Or: printf '...some valid assembly...' | ./integrate
#

set -e -o pipefail

mkdir -p out/storage

./scripts/asm | awk '{print NR-1 " => " "\"" $0 "\","}' | sed -e '/--%REPLACE%--/{r /dev/stdin' -e 'd;}' src/storage/instr_mem.vhdl >out/storage/instr_mem.vhdl
exec env RUN_MAIN=1 ./run-test main_tb
