add wave -position end  sim:/main/ccr
add wave -position end  sim:/main/xs_ccr
add wave -position end  sim:/main/ms_ccr
add wave -position end  sim:/main/ms_ccr_sel
add wave -position end  sim:/main/xs_ccr_sel
add wave -position end  sim:/main/hdu_stall
add wave -position end  sim:/main/hdu_xs_op_1_sel
add wave -position end  sim:/main/hdu_xs_op_2_sel
add wave -position end  sim:/main/fsi_if_flush
add wave -position end  sim:/main/fsi_parallel_load_pc_selector
add wave -position end  sim:/main/fsi_branch_address
add wave -position end  sim:/main/fsi_hashed_address
add wave -position end  sim:/main/fsi_out_reg_idx
add wave -position end  sim:/main/fsi_in_reg_value
add wave -position end  sim:/main/fs_fdb_interrupt
add wave -position end  sim:/main/fs_fdb_instruction_bits
add wave -position end  sim:/main/fs_fdb_predicted_address
add wave -position end  sim:/main/fs_fdb_hashed_address
add wave -position end  sim:/main/fs_fdb_inc_pc
add wave -position end  sim:/main/fdb_ds_instr
add wave -position end  sim:/main/fdb_ds_inc_pc
add wave -position end  sim:/main/fdb_ds_next_adr
add wave -position end  sim:/main/fdb_ds_hashed_adr
add wave -position end  sim:/main/fdb_ds_interrupt
add wave -position end  sim:/main/ds_dxb_alu_op
add wave -position end  sim:/main/ds_dxb_dest_0
add wave -position end  sim:/main/ds_dxb_dest_1
add wave -position end  sim:/main/ds_dxb_opcode
add wave -position end  sim:/main/ds_dxb_r_w
add wave -position end  sim:/main/ds_dxb_interrupt
add wave -position end  sim:/main/ds_dxb_src2_value
add wave -position end  sim:/main/ds_dxb_src2_sel
add wave -position end  sim:/main/ds_dxb_hlt
add wave -position end  sim:/main/ds_rf_src0_adr
add wave -position end  sim:/main/ds_rf_src1_adr
add wave -position end  sim:/main/ds_rf_br_io_enbl
add wave -position end  sim:/main/rf_ds_instr_adr
add wave -position end  sim:/main/rf_dxb_op0_value
add wave -position end  sim:/main/rf_dxb_op1_value
add wave -position end  sim:/main/dxb_xs_alu_op
add wave -position end  sim:/main/dxb_xs_operand0
add wave -position end  sim:/main/dxb_xs_operand1
add wave -position end  sim:/main/dxb_xs_dest_0
add wave -position end  sim:/main/dxb_xs_dest_1
add wave -position end  sim:/main/dxb_xs_opcode
add wave -position end  sim:/main/dxb_xs_r_w
add wave -position end  sim:/main/dxb_xs_interrupt
add wave -position end  sim:/main/dxb_xs_hlt
add wave -position end  sim:/main/rf_dst0_adr
add wave -position end  sim:/main/rf_dst1_adr
add wave -position end  sim:/main/rf_src0_adr
add wave -position end  sim:/main/rf_src1_adr
add wave -position end  sim:/main/rf_wb0_value
add wave -position end  sim:/main/rf_br_io_enbl
add wave -position end  sim:/main/rf_rst
add wave -position end  sim:/main/xs_xmb_alu_output_1
add wave -position end  sim:/main/xs_xmb_alu_output_2
add wave -position end  sim:/main/xs_xmb_interpt
add wave -position end  sim:/main/xs_xmb_destination_0
add wave -position end  sim:/main/xs_xmb_destination_1
add wave -position end  sim:/main/xs_xmb_mem_adr
add wave -position end  sim:/main/xs_xmb_mem_input
add wave -position end  sim:/main/xs_xmb_opcode
add wave -position end  sim:/main/xs_xmb_r_w
add wave -position end  sim:/main/xs_xmb_hlt
add wave -position end  sim:/main/xs_hdu_src_0
add wave -position end  sim:/main/xs_hdu_src_1
add wave -position end  sim:/main/ms_stalling_enable
add wave -position end  sim:/main/xmb_ms_xs_aluout_1
add wave -position end  sim:/main/xmb_ms_xs_aluout_2
add wave -position end  sim:/main/xmb_ms_mem_adr
add wave -position end  sim:/main/xmb_ms_mem_input
add wave -position end  sim:/main/xmb_ms_opcode
add wave -position end  sim:/main/xmb_ms_destination_0
add wave -position end  sim:/main/xmb_ms_destination_1
add wave -position end  sim:/main/xmb_ms_r_w
add wave -position end  sim:/main/xmb_ms_interrupt
add wave -position end  sim:/main/xmb_ms_hlt
add wave -position end  sim:/main/ms_mwb_aluout_1
add wave -position end  sim:/main/ms_mwb_aluout_2
add wave -position end  sim:/main/ms_mwb_mem_input
add wave -position end  sim:/main/ms_mwb_opcode
add wave -position end  sim:/main/ms_mwb_dest_0_adr
add wave -position end  sim:/main/ms_mwb_dest_1_adr
add wave -position end  sim:/main/ms_mwb_hlt
add wave -position end  sim:/main/mwb_ws_aluout_1
add wave -position end  sim:/main/mwb_ws_aluout_2
add wave -position end  sim:/main/mwb_ws_xs_mem
add wave -position end  sim:/main/mwb_ws_opcode
add wave -position end  sim:/main/mwb_ws_destination_0
add wave -position end  sim:/main/mwb_ws_destination_1
add wave -position end  sim:/main/mwb_ws_hlt
add wave -position end  sim:/main/ws_rf_dest_reg_1
add wave -position end  sim:/main/ws_rf_dest_reg_2
add wave -position end  sim:/main/ws_rf_dest_reg_1_value
add wave -position end  sim:/main/ws_rf_dest_reg_2_value